#ifndef GRAMMAR_H
#define GRAMMAR_H

enum Expr_Type {
  EXPR_TYPE_BIN,
  EXPR_TYPE_UNARY,
  EXPR_TYPE_INT_LIT,
  EXPR_TYPE_STR_LIT,
  EXPR_TYPE_IDENTIFIER,
  EXPR_TYPE_MUT,
};

enum Stmt_Type {
  STMT_TYPE_LET,
  STMT_TYPE_FUNC,
  STMT_TYPE_IF,
  STMT_TYPE_WHILE,
  STMT_TYPE_FOR,
};

#endif // GRAMMAR_H